// pagination-nextjs-example/app/infinite-scroll/page.tsx
import { getArticlesPage } from '@/lib/api';
import Link from 'next/link';
import InfiniteScrollClient from './infinite-scroll-client';

interface PageProps {
  searchParams: Promise<{
    page?: string;
  }>;
}

const ITEMS_PER_PAGE = 10;

export default async function InfiniteScroll({ searchParams }: PageProps) {
  const params = await searchParams;
  const currentPage = parseInt(params.page || '1', 10);

  // Fetch all pages up to current page
  const allArticles = [];
  let hasMore = true;

  for (let page = 1; page <= currentPage; page++) {
    const { data: articles } = await getArticlesPage(page, ITEMS_PER_PAGE, {
      locale: 'en',
    });

    if (articles.length > 0) {
      allArticles.push(...articles);
      if (articles.length < ITEMS_PER_PAGE) {
        hasMore = false;
        break;
      }
    } else {
      hasMore = false;
      break;
    }
  }

  // Check if there's more by fetching next page
  if (hasMore) {
    const { data: nextPageArticles } = await getArticlesPage(
      currentPage + 1,
      ITEMS_PER_PAGE,
      { locale: 'en' }
    );
    hasMore = nextPageArticles.length > 0;
  }

  return (
    <div className="container">
      <header>
        <Link href="/" style={{ color: 'var(--primary)', textDecoration: 'none', marginBottom: '1rem', display: 'inline-block' }}>
          ← Back to Examples
        </Link>
        <h1>Infinite Scroll</h1>
        <p>
          Automatically loads more content as you scroll using Intersection Observer
        </p>
      </header>

      {allArticles.length === 0 ? (
        <div className="loading">No articles found.</div>
      ) : (
        <>
          <div className="articles-list">
            {allArticles.map((article) => (
              <article key={article.uuid} className="article-card">
                <div className="article-card-header">
                  <h2>{article.fields.title}</h2>
                  <div className="article-meta">
                    {article.fields.category && (
                      <span className="category-badge">{article.fields.category}</span>
                    )}
                    {article.fields.published_date && (
                      <span>
                        📅 {new Date(article.fields.published_date).toLocaleDateString('en-US', {
                          year: 'numeric',
                          month: 'long',
                          day: 'numeric',
                        })}
                      </span>
                    )}
                    {article.fields.views && (
                      <span>👁️ {parseInt(article.fields.views).toLocaleString()} views</span>
                    )}
                  </div>
                  {article.fields.excerpt && (
                    <p className="excerpt">{article.fields.excerpt}</p>
                  )}
                </div>
              </article>
            ))}
          </div>

          <InfiniteScrollClient currentPage={currentPage} hasMore={hasMore} />
        </>
      )}
    </div>
  );
}

// pagination-nuxtjs-example/pages/infinite-scroll.vue
<template>
  <div class="container">
    <header>
      <NuxtLink to="/" class="back-link">← Back to Examples</NuxtLink>
      <h1>Infinite Scroll</h1>
      <p>
        Automatically loads more content as you scroll using Intersection Observer
      </p>
    </header>

    <div v-if="allArticles.length === 0" class="loading">
      No articles found.
    </div>

    <template v-else>
      <div class="articles-list">
        <article v-for="article in allArticles" :key="article.uuid" class="article-card">
          <div class="article-card-header">
            <h2>{{ article.fields.title }}</h2>
            <div class="article-meta">
              <span v-if="article.fields.category" class="category-badge">
                {{ article.fields.category }}
              </span>
              <span v-if="article.fields.published_date">
                📅 {{ formatDate(article.fields.published_date) }}
              </span>
              <span v-if="article.fields.views">
                👁️ {{ formatViews(article.fields.views) }} views
              </span>
            </div>
            <p v-if="article.fields.excerpt" class="excerpt">
              {{ article.fields.excerpt }}
            </p>
          </div>
        </article>
      </div>

      <InfiniteScrollClient :current-page="currentPage" :has-more="hasMore" />
    </template>
  </div>
</template>

<script setup lang="ts">
const route = useRoute();
const { getArticlesPage } = useElmapi();

const ITEMS_PER_PAGE = 10;
const currentPage = computed(() => parseInt((route.query.page as string) || '1', 10));

// Store all articles and track which pages we've loaded
const allArticles = ref<any[]>([]);
const loadedPages = ref<Set<number>>(new Set());
const hasMore = ref(true);

// Fetch a single page (useAsyncData automatically caches by key)
async function fetchPage(page: number) {
  const { data } = await useAsyncData(
    `articles-infinite-page-${page}`,
    () => getArticlesPage(page, ITEMS_PER_PAGE, { locale: 'en' })
  );
  return data.value;
}

// Load all pages up to current page
async function loadPages() {
  // Only fetch pages we haven't loaded yet
  for (let page = 1; page <= currentPage.value; page++) {
    if (!loadedPages.value.has(page)) {
      const articlesResult = await fetchPage(page);
      const articles = articlesResult?.data || [];
      
      if (articles.length > 0) {
        allArticles.value.push(...articles);
        loadedPages.value.add(page);
        
        if (articles.length < ITEMS_PER_PAGE) {
          hasMore.value = false;
          break;
        }
      } else {
        hasMore.value = false;
        break;
      }
    }
  }

  // Check if there's more (only check when we've loaded a new page)
  if (hasMore.value) {
    const nextPage = currentPage.value + 1;
    // Only check if we haven't already loaded this page
    if (!loadedPages.value.has(nextPage)) {
      const { data: nextPageData } = await useAsyncData(
        `articles-infinite-check-next-${nextPage}`,
        () => getArticlesPage(nextPage, ITEMS_PER_PAGE, { locale: 'en' })
      );
      hasMore.value = (nextPageData.value?.data || []).length > 0;
    }
  }
}

// Initial load
await loadPages();

// Watch for page changes and only load new pages (when page increases)
watch(currentPage, async (newPage, oldPage) => {
  if (newPage > (oldPage || 0)) {
    await loadPages();
  }
});

function formatDate(dateString: string) {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatViews(views: string) {
  return parseInt(views).toLocaleString();
}
</script>

<style scoped>
.back-link {
  color: var(--primary);
  text-decoration: none;
  margin-bottom: 1rem;
  display: inline-block;
}
</style>
