// pagination-nextjs-example/app/blog/page.tsx
import { getArticlesPage, getCategories } from '@/lib/api';
import Link from 'next/link';
import Filters from './filters';
import { generatePageNumbers } from '@/lib/pagination';

interface BlogPageProps {
  searchParams: Promise<{
    page?: string;
    category?: string;
    search?: string;
    sort?: string;
    per_page?: string;
  }>;
}

export default async function BlogPage({ searchParams }: BlogPageProps) {
  const params = await searchParams;
  const currentPage = parseInt(params.page || '1', 10);
  const perPage = parseInt(params.per_page || '10', 10);
  const category = params.category || undefined;
  const search = params.search || undefined;
  const sort = params.sort || 'id:ASC';

  const [articlesResult, categories] = await Promise.all([
    getArticlesPage(currentPage, perPage, {
      category,
      search,
      sort,
      locale: 'en',
    }),
    getCategories('en'),
  ]);

  const { data: articles, page, perPage: itemsPerPage, total } = articlesResult;
  const hasMore = articles.length === itemsPerPage;
  const totalPages = total ? Math.ceil(total / itemsPerPage) : undefined;
  const pageNumbers = totalPages ? generatePageNumbers(page, totalPages) : [];

  // Helper function to build URL with all query params
  const buildPageUrl = (pageNum: number) => {
    return `/blog?${new URLSearchParams({
      ...(category && { category }),
      ...(search && { search }),
      ...(sort && { sort }),
      ...(itemsPerPage !== 10 && { per_page: String(itemsPerPage) }),
      page: String(pageNum),
    }).toString()}`;
  };

  return (
    <div className="container">
      <header>
        <Link href="/" style={{ color: 'var(--primary)', textDecoration: 'none', marginBottom: '1rem', display: 'inline-block' }}>
          ← Back to Examples
        </Link>
        <h1>ElmapiCMS Blog</h1>
        <p>Advanced filtering, sorting, and pagination powered by ElmapiCMS</p>
      </header>

      <Filters categories={categories} currentFilters={{ category, search, sort, per_page: itemsPerPage }} />

      {articles.length === 0 ? (
        <div className="loading">
          <p>No articles found.</p>
          {(category || search) && (
            <p style={{ marginTop: '1rem' }}>
              Try adjusting your filters or{' '}
              <Link href="/blog" style={{ color: 'var(--primary)' }}>
                clear all filters
              </Link>
              .
            </p>
          )}
        </div>
      ) : (
        <>
          <div className="articles-list">
            {articles.map((article) => (
              <article key={article.uuid} className="article-card">
                <div className="article-card-header">
                  <h2>
                    <Link href={`/blog/${article.uuid}`}>{article.fields.title}</Link>
                  </h2>
                  <div className="article-meta">
                    {article.fields.category && (
                      <span className="category-badge">{article.fields.category}</span>
                    )}
                    {article.fields.published_date && (
                      <span>
                        📅 {new Date(article.fields.published_date).toLocaleDateString('en-US', {
                          year: 'numeric',
                          month: 'long',
                          day: 'numeric',
                        })}
                      </span>
                    )}
                    {article.fields.views && (
                      <span>👁️ {parseInt(article.fields.views).toLocaleString()} views</span>
                    )}
                  </div>
                  {article.fields.excerpt && (
                    <p className="excerpt">{article.fields.excerpt}</p>
                  )}
                </div>
                <div className="article-card-footer">
                  <Link href={`/blog/${article.uuid}`} className="read-more">
                    Read More →
                  </Link>
                </div>
              </article>
            ))}
          </div>

          <div className="pagination">
            {page > 1 && (
              <Link href={buildPageUrl(page - 1)}>
                <button>Previous</button>
              </Link>
            )}

            {pageNumbers.length > 0 ? (
              <>
                {pageNumbers.map((pageNum, index) => {
                  if (pageNum === '...') {
                    return (
                      <span key={`ellipsis-${index}`} className="pagination-ellipsis">
                        ...
                      </span>
                    );
                  }
                  const pageNumValue = pageNum as number;
                  return (
                    <Link key={pageNumValue} href={buildPageUrl(pageNumValue)}>
                      <button className={pageNumValue === page ? 'active' : ''}>
                        {pageNumValue}
                      </button>
                    </Link>
                  );
                })}
              </>
            ) : (
              <span className="pagination-info">
                Page {page}
                {totalPages && ` of ${totalPages}`}
              </span>
            )}

            {hasMore && (
              <Link href={buildPageUrl(page + 1)}>
                <button>Next</button>
              </Link>
            )}
          </div>

          <div className="info-card" style={{ marginTop: '2rem' }}>
            <h3 style={{ marginBottom: '1rem', fontSize: '1.1rem', fontWeight: 600, color: 'var(--text)' }}>
              Pagination Info
            </h3>
            <div className="info-stats">
              <div className="info-stat">
                <span className="info-stat-label">Current Page</span>
                <span className="info-stat-value">{page}</span>
              </div>
              <div className="info-stat">
                <span className="info-stat-label">Items Per Page</span>
                <span className="info-stat-value">{itemsPerPage}</span>
              </div>
              <div className="info-stat">
                <span className="info-stat-label">Items on This Page</span>
                <span className="info-stat-value">{articles.length}</span>
              </div>
              {total !== undefined && total !== null && typeof total === 'number' && (
                <div className="info-stat">
                  <span className="info-stat-label">Total Items</span>
                  <span className="info-stat-value">{total.toLocaleString()}</span>
                </div>
              )}
              {totalPages && (
                <div className="info-stat">
                  <span className="info-stat-label">Total Pages</span>
                  <span className="info-stat-value">{totalPages}</span>
                </div>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// pagination-nuxtjs-example/pages/blog/index.vue
<template>
  <div class="container">
    <header>
      <NuxtLink to="/" class="back-link">← Back to Examples</NuxtLink>
      <h1>ElmapiCMS Blog</h1>
      <p>Advanced filtering, sorting, and pagination powered by ElmapiCMS</p>
    </header>

    <BlogFilters
      :categories="categories"
      :current-filters="{ category, search, sort, per_page: itemsPerPage }"
    />

    <div v-if="articles.length === 0" class="loading">
      <p>No articles found.</p>
      <p v-if="category || search" style="margin-top: 1rem">
        Try adjusting your filters or
        <NuxtLink to="/blog" style="color: var(--primary)">clear all filters</NuxtLink>.
      </p>
    </div>

    <template v-else>
      <div class="articles-list">
        <article v-for="article in articles" :key="article.uuid" class="article-card">
          <div class="article-card-header">
            <h2>
              <NuxtLink :to="`/blog/${article.uuid}`">{{ article.fields.title }}</NuxtLink>
            </h2>
            <div class="article-meta">
              <span v-if="article.fields.category" class="category-badge">
                {{ article.fields.category }}
              </span>
              <span v-if="article.fields.published_date">
                📅 {{ formatDate(article.fields.published_date) }}
              </span>
              <span v-if="article.fields.views">
                👁️ {{ formatViews(article.fields.views) }} views
              </span>
            </div>
            <p v-if="article.fields.excerpt" class="excerpt">
              {{ article.fields.excerpt }}
            </p>
          </div>
          <div class="article-card-footer">
            <NuxtLink :to="`/blog/${article.uuid}`" class="read-more">
              Read More →
            </NuxtLink>
          </div>
        </article>
      </div>

      <div class="pagination">
        <NuxtLink v-if="page > 1" :to="buildPageUrl(page - 1)">
          <button>Previous</button>
        </NuxtLink>

        <template v-if="pageNumbers.length > 0">
          <template v-for="(pageNum, index) in pageNumbers" :key="index">
            <span v-if="pageNum === '...'" class="pagination-ellipsis">
              ...
            </span>
            <NuxtLink v-else :to="buildPageUrl(pageNum as number)">
              <button :class="{ active: pageNum === page }">
                {{ pageNum }}
              </button>
            </NuxtLink>
          </template>
        </template>
        <span v-else class="pagination-info">
          Page {{ page }}
          <span v-if="totalPages"> of {{ totalPages }}</span>
        </span>

        <NuxtLink v-if="hasMore" :to="buildPageUrl(page + 1)">
          <button>Next</button>
        </NuxtLink>
      </div>

      <div class="info-card" style="margin-top: 2rem">
        <h3 style="margin-bottom: 1rem; font-size: 1.1rem; font-weight: 600; color: var(--text)">
          Pagination Info
        </h3>
        <div class="info-stats">
          <div class="info-stat">
            <span class="info-stat-label">Current Page</span>
            <span class="info-stat-value">{{ page }}</span>
          </div>
          <div class="info-stat">
            <span class="info-stat-label">Items Per Page</span>
            <span class="info-stat-value">{{ itemsPerPage }}</span>
          </div>
          <div class="info-stat">
            <span class="info-stat-label">Items on This Page</span>
            <span class="info-stat-value">{{ articles.length }}</span>
          </div>
          <div v-if="total !== undefined && total !== null && typeof total === 'number'" class="info-stat">
            <span class="info-stat-label">Total Items</span>
            <span class="info-stat-value">{{ formatNumber(total) }}</span>
          </div>
          <div v-if="totalPages" class="info-stat">
            <span class="info-stat-label">Total Pages</span>
            <span class="info-stat-value">{{ totalPages }}</span>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
const route = useRoute();
const { getArticlesPage, getCategories } = useElmapi();
const { generatePageNumbers } = usePagination();

const currentPage = computed(() => parseInt((route.query.page as string) || '1', 10));
const perPage = computed(() => parseInt((route.query.per_page as string) || '10', 10));
const category = computed(() => (route.query.category as string) || undefined);
const search = computed(() => (route.query.search as string) || undefined);
const sort = computed(() => (route.query.sort as string) || 'id:ASC');

const { data: articlesResult } = await useAsyncData(
  () => `articles-blog-${currentPage.value}-${perPage.value}-${category.value || ''}-${search.value || ''}-${sort.value}`,
  () => getArticlesPage(currentPage.value, perPage.value, {
    category: category.value,
    search: search.value,
    sort: sort.value,
    locale: 'en',
  }),
  {
    watch: [currentPage, perPage, category, search, sort]
  }
);

const { data: categories } = await useAsyncData('categories', () => getCategories('en'));

const articles = computed(() => articlesResult.value?.data || []);
const page = computed(() => articlesResult.value?.page || 1);
const itemsPerPage = computed(() => articlesResult.value?.perPage || 10);
const total = computed(() => articlesResult.value?.total);
const hasMore = computed(() => articles.value.length === itemsPerPage.value);
const totalPages = computed(() => total.value ? Math.ceil(total.value / itemsPerPage.value) : undefined);
const pageNumbers = computed(() => totalPages.value ? generatePageNumbers(page.value, totalPages.value) : []);

function buildPageUrl(pageNum: number) {
  const params = new URLSearchParams();
  if (category.value) params.set('category', category.value);
  if (search.value) params.set('search', search.value);
  if (sort.value) params.set('sort', sort.value);
  if (itemsPerPage.value !== 10) params.set('per_page', String(itemsPerPage.value));
  params.set('page', String(pageNum));
  return `/blog?${params.toString()}`;
}

function formatDate(dateString: string) {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatViews(views: string) {
  return parseInt(views).toLocaleString();
}

function formatNumber(num: number) {
  return num.toLocaleString();
}
</script>

<style scoped>
.back-link {
  color: var(--primary);
  text-decoration: none;
  margin-bottom: 1rem;
  display: inline-block;
}
</style>
