// pagination-nextjs-example/app/load-more/load-more-button.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useEffect } from 'react';

interface LoadMoreButtonProps {
  nextPage: number;
}

export default function LoadMoreButton({ nextPage }: LoadMoreButtonProps) {
  const router = useRouter();

  useEffect(() => {
    // Restore scroll position after navigation and content render
    const restoreScroll = () => {
      const savedPosition = sessionStorage.getItem('load-more-position');
      if (savedPosition) {
        requestAnimationFrame(() => {
          window.scrollTo(0, parseInt(savedPosition, 10));
          sessionStorage.removeItem('load-more-position');
        });
      }
    };

    // Use setTimeout to ensure DOM is updated
    const timeoutId = setTimeout(restoreScroll, 0);
    return () => clearTimeout(timeoutId);
  });

  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    e.preventDefault();
    // Save current scroll position before navigation
    sessionStorage.setItem('load-more-position', String(window.scrollY));
    router.push(`/load-more?page=${nextPage}`);
  };

  return (
    <a
      href={`/load-more?page=${nextPage}`}
      onClick={handleClick}
      className="load-more-btn"
      style={{ marginTop: '2rem', display: 'inline-block' }}
    >
      Load More
    </a>
  );
}

// pagination-nuxtjs-example/components/LoadMoreButton.vue
<template>
  <NuxtLink
    :to="`/load-more?page=${nextPage}`"
    class="load-more-btn"
    style="margin-top: 2rem; display: inline-block"
    @click="handleClick"
  >
    Load More
  </NuxtLink>
</template>

<script setup lang="ts">
interface Props {
  nextPage: number;
}

const props = defineProps<Props>();
const router = useRouter();

onMounted(() => {
  // Restore scroll position after navigation and content render
  const restoreScroll = () => {
    const savedPosition = sessionStorage.getItem('load-more-position');
    if (savedPosition) {
      requestAnimationFrame(() => {
        window.scrollTo(0, parseInt(savedPosition, 10));
        sessionStorage.removeItem('load-more-position');
      });
    }
  };

  // Use setTimeout to ensure DOM is updated
  setTimeout(restoreScroll, 0);
});

const handleClick = (e: Event) => {
  e.preventDefault();
  // Save current scroll position before navigation
  sessionStorage.setItem('load-more-position', String(window.scrollY));
  router.push(`/load-more?page=${props.nextPage}`);
};
</script>
